name: "{{ project_id_tgt }}.{{ marketing_meta_datasets_reporting }}.CampaignInsightsByPlatform"
description: "Campaign facts at Campaign, date and platform level."
fields:
  - name: "report_date"
    description: "Report date."
  - name: "campaign_id"
    description: "The unique ID number of the ad campaign you're viewing in reporting. Your campaign contains ad sets and ads."
  - name: "publisher_platform"
    description: "Which platform your ad was shown, for example on Facebook, Instagram, or Audience Network."
  - name: "account_id"
    description: "The ID number of your ad account, which groups your advertising activity. "
  - name: "account_currency"
    description: "Currency that is used by your ad account"
  - name: "account_name"
    description: "The name of your ad account, which groups your advertising activity. "
  - name: "action_values"
    description: "The total value of all conversions attributed to your ads."
  - name: "actions"
    description: "The total number of actions people took that are attributed to your ads. Actions may include engagement, clicks or conversions."
  - name: "ad_click_actions"
    description: "ad_click_actions"
  - name: "ad_impression_actions"
    description: "ad_impression_actions"
  - name: "attribution_setting"
    description: "The default attribution window to be used when attribution result is calculated."
  - name: "auction_bid"
    description: "auction_bid"
  - name: "auction_competitiveness"
    description: "auction_competitiveness"
  - name: "auction_max_competitor_bid"
    description: "auction_max_competitor_bid"
  - name: "buying_type"
    description: "The method by which you pay for and target ads in your campaigns: through dynamic auction bidding, fixed-price bidding, or reach and frequency buying. "
  - name: "campaign_name"
    description: "The name of the ad campaign you're viewing in reporting. Your campaign contains ad sets and ads."
  - name: "canvas_avg_view_percent"
    description: "The average percentage of the Instant Experience that people saw. "
  - name: "canvas_avg_view_time"
    description: "The average total time, in seconds, that people spent viewing an Instant Experience. "
  - name: "catalog_segment_actions"
    description: "The number of actions performed attributed to your ads promoting your catalog segment, broken down by action type."
  - name: "catalog_segment_value"
    description: "The total value of all conversions from your catalog segment attributed to your ads."
  - name: "clicks"
    description: "The number of clicks on your ads."
  - name: "conversion_values"
    description: "The total value of all conversions attributed to your ads."
  - name: "cost_per_dda_countby_convs"
    description: "cost_per_dda_countby_convs"
  - name: "cost_per_inline_link_click"
    description: "The average cost of each inline link click."
  - name: "cost_per_inline_post_engagement"
    description: "The average cost of each inline post engagement."
  - name: "cost_per_one_thousand_ad_impression"
    description: "cost_per_one_thousand_ad_impression"
  - name: "cost_per_outbound_click"
    description: "The average cost for each outbound click."
  - name: "cost_per_thruplay"
    description: "The average cost for each ThruPlay. This metric is in development."
  - name: "cost_per_unique_action_type"
    description: "The average cost of each unique action. This metric is estimated."
  - name: "cost_per_unique_click"
    description: "The average cost for each unique click (all). This metric is estimated."
  - name: "cost_per_unique_inline_link_click"
    description: "The average cost of each unique inline link click. This metric is estimated."
  - name: "cost_per_unique_outbound_click"
    description: "The average cost for each unique outbound click. This metric is estimated."
  - name: "cpc"
    description: "The average cost for each click (all)."
  - name: "cpm"
    description: "The average cost for 1,000 impressions."
  - name: "cpp"
    description: "The average cost to reach 1,000 people. This metric is estimated."
  - name: "created_date"
    description: "created date of the campaign, derived from created_time"
  - name: "ctr"
    description: "The percentage of times people saw your ad and performed a click (all)."
  - name: "date_start"
    description: "The start date for your data. This is controlled by the date range you've selected for your reporting view."
  - name: "date_stop"
    description: "The end date for your data. This is controlled by the date range you've selected for your reporting view."
  - name: "dda_countby_convs"
    description: "dda_countby_convs"
  - name: "dda_results"
    description: "dda_results"
  - name: "frequency"
    description: "The average number of times each person saw your ad. This metric is estimated."
  - name: "full_view_impressions"
    description: "The number of Full Views on your Page's posts as a result of your ad."
  - name: "full_view_reach"
    description: "The number of people who performed a Full View on your Page's post as a result of your ad."
  - name: "impressions"
    description: "The number of times your ads were on screen."
  - name: "inline_link_click_ctr"
    description: "The percentage of time people saw your ads and performed an inline link click."
  - name: "inline_link_clicks"
    description: "The number of clicks on links to select destinations or experiences, on or off Facebook-owned properties. "
  - name: "inline_post_engagement"
    description: "The total number of actions that people take involving your ads. Inline post engagements use a fixed 1-day-click attribution window."
  - name: "instant_experience_clicks_to_open"
    description: "instant_experience_clicks_to_open"
  - name: "instant_experience_clicks_to_start"
    description: "instant_experience_clicks_to_start"
  - name: "instant_experience_outbound_clicks"
    description: "instant_experience_outbound_clicks"
  - name: "interactive_component_tap"
    description: "interactive_component_tap"
  - name: "mobile_app_purchase_roas"
    description: "The total return on ad spend (ROAS) from mobile app purchases. This is based on the value that you assigned when you set up the app event."
  - name: "objective"
    description: "The objective reflecting the goal you want to achieve with your advertising. It may be different from the selected objective of the campaign in some cases."
  - name: "optimization_goal"
    description: "The optimization goal you selected for your ad or ad set. Your optimization goal reflects what you want to optimize for the ads."
  - name: "outbound_clicks"
    description: "The number of clicks on links that take people off Facebook-owned properties."
  - name: "outbound_clicks_ctr"
    description: "The percentage of times people saw your ad and performed an outbound click."
  - name: "place_page_name"
    description: "The name of the place page involved in impression or click. Has to be used together with Business Locations breakdown."
  - name: "purchase_roas"
    description: "The total return on ad spend (ROAS) from purchases. This is based on information received from one or more of your connected Facebook Business Tools and attributed to your ads."
  - name: "qualifying_question_qualify_answer_rate"
    description: "qualifying_question_qualify_answer_rate"
  - name: "reach"
    description: "The number of people who saw your ads at least once. "
  - name: "social_spend"
    description: "The total amount you've spent so far for your ads showed with social information. (ex: Jane Doe likes this)."
  - name: "spend"
    description: "The estimated total amount of money you've spent on your campaign, ad set or ad during its schedule. This metric is estimated."
  - name: "updated_date"
    description: "updated date of the campaign, derived from updated_time"
  - name: "video_30_sec_watched_actions"
    description: "The number of times your video played for at least 30 seconds, or for nearly its total length if it's shorter than 30 seconds. For each impression of a video, we'll count video views separately and exclude any time spent replaying the video."
  - name: "video_avg_time_watched_actions"
    description: "The average time a video was played, including any time spent replaying the video for a single impression."
  - name: "video_continuous_2_sec_watched_actions"
    description: "video_continuous_2_sec_watched_actions"
  - name: "video_p100_watched_actions"
    description: "The number of times your video was played at 100% of its length, including plays that skipped to this point."
  - name: "video_p25_watched_actions"
    description: "The number of times your video was played at 25% of its length, including plays that skipped to this point."
  - name: "video_p50_watched_actions"
    description: "The number of times your video was played at 50% of its length, including plays that skipped to this point."
  - name: "video_p75_watched_actions"
    description: "The number of times your video was played at 75% of its length, including plays that skipped to this point."
  - name: "video_p95_watched_actions"
    description: "The number of times your video was played at 95% of its length, including plays that skipped to this point."
  - name: "video_play_actions"
    description: "The number of times your video starts to play. This is counted for each impression of a video, and excludes replays. This metric is in development."
  - name: "video_play_curve_actions"
    description: "A video-play based curve graph that illustrates the percentage of video plays that reached a given second. Entries 0 to 14 represent seconds 0 thru 14. Entries 15 to 17 represent second ranges [15 to 20), [20 to 25), and [25 to 30). Entries 18 to 20 represent second ranges [30 to 40), [40 to 50), and [50 to 60). Entry 21 represents plays over 60 seconds."
  - name: "video_play_retention_0_to_15s_actions"
    description: "video_play_retention_0_to_15s_actions"
  - name: "video_play_retention_20_to_60s_actions"
    description: "video_play_retention_20_to_60s_actions"
  - name: "video_play_retention_graph_actions"
    description: "video_play_retention_graph_actions"
  - name: "video_time_watched_actions"
    description: "video_time_watched_actions"
  - name: "website_ctr"
    description: "The percentage of times people saw your ad and performed a link click."
  - name: "website_purchase_roas"
    description: "The total return on ad spend (ROAS) from website purchases. This is based on the value of all conversions recorded by the Facebook pixel on your website and attributed to your ads."
